In [1]:
import pandas as pd; import warnings; warnings.filterwarnings("ignore")
import os
import numpy as np

C:\Users\Raunak.Ravi\OneDrive - GlobalData PLC\Documents\projects\Innovation Scorecard\Dec 2024\Final data\IS_input_raw-data_08012025.xlsx

In [2]:
os.chdir("C:\\Users\\Raunak.Ravi\\OneDrive - GlobalData PLC\\Documents\\projects\\Innovation Scorecard\\Dec 2024\\Final data\\Data_output")

In [3]:
os.getcwd()

'C:\\Users\\Raunak.Ravi\\OneDrive - GlobalData PLC\\Documents\\projects\\Innovation Scorecard\\Dec 2024\\Final data\\Data_output'

In [4]:
data = pd.read_excel('IS_input_raw-data_28012025.xlsx', ['10_years','5_years','3_years'])
print(data.keys()); Out = pd.DataFrame()

dict_keys(['10_years', '5_years', '3_years'])

In [5]:
# Qualitative columns
df_qual = data['10_years'].iloc[:,:7]
df_qual.info();display(df_qual)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6993 entries, 0 to 6992
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CDMS ID          6993 non-null   int64
 1   Company Name     6993 non-null   object
 2   Stock Ticker     3957 non-null   object
 3   Stock Exchange   3957 non-null   object
 4   Country (HQ)     6948 non-null   object
 5   Sector           6843 non-null   object
 6   Theme            1805 non-null   object
dtypes: int64(1), object(6)
memory usage: 382.6+ KB

,CDMS ID,Company Name,Stock Ticker,Stock Exchange,Country (HQ),Sector,Theme
0,1000749,AB Volvo,VOLV B,Stockholm Stock Exchange,Sweden,Automotive,Theme - Industry - Automotive - Autonomous Veh...
1,1001749,Aichi Corp,6345,Tokyo Stock Exchange,Japan,Automotive,NaN
2,1002130,Aida Engineering Ltd,6118,Tokyo Stock Exchange,Japan,Industrial Goods and Machinery,NaN
3,1002605,PORR AG,POS,Vienna Stock Exchange - Cash Market,Austria,Construction,NaN
4,1002842,Anhui Ankai Automobile Co Ltd,000868,Shenzhen Stock Exchange,China,Automotive,NaN
...,...,...,...,...,...,...,...
6988,5196234,Liu Ting Ting,NaN,NaN,Hong Kong (China SAR),General Business,NaN
6989,5199220,Trellix,NaN,NaN,United States,Technology and Communications,Theme - Technology - Cybersecurity; Theme - Te...
6990,5221636,"BFLY Operations, Inc.",NaN,NaN,United States,NaN,NaN
6991,5240689,"i-PRO Co., Ltd",NaN,NaN,Japan,Technology and Communications,NaN
6992,5255562,AutoStore Technology AS,NaN,NaN,Norway,Technology and Communications,NaN

In [6]:
## 10 years

In [7]:
## 10 years
df10 = data['10_years'].copy()
#df10.info(); display(df10)
# keeping relevant columns
df10 = df10[['CDMS ID'] + df10.columns[7:].to_list()]
# column of interest
COI = ['Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 
       'Share of Self-Cited Patents', 
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes']
# Min-max normalization
for col in COI:
    # Calculate min-max normalized values for selected columns
    min_value = df10[col].min()
    max_value = df10[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = 0.01 + (df10[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df10[new_col_name] = normalized_values_rounded

COI_2 = ['Innovation Sentiment']
import numpy as np

for col in COI_2:
    # Calculate min-max normalized values for selected columns
    min_value = df10[col].min()
    max_value = df10[col].max()

    # Adjusted normalized values calculation with condition
    normalized_values_rounded = np.where(
        df10[col].isna(),  # Condition to check if the value is NaN (blank)
        0.01,  # Value if condition is true
        0.01 + (df10[col] - min_value) * (1 - 0.01) / (max_value - min_value)  # Value if condition is false
    )
    
    #normalized_values_rounded = np.round(normalized_values, 2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df10[new_col_name] = normalized_values_rounded

In [9]:
COI_3 = ['Patents Portfolio Validity']
for col in COI_3:
    # Calculate min-max normalized values for selected columns
    min_value = df10[col].min()
    max_value = df10[col].max()

    # Step 1: Set to 0 if df10[col] < 0
    intermediate_values = df10[col].apply(lambda x: 0 if x < 0 else x)

    # Step 2: Calculate using the formula on intermediate values
    #normalized_values = 0.01 + (df10[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    normalized_values_rounded = intermediate_values.apply(
        lambda x: 0.01 + ((x - min_value) * (1 - 0.01)) / (max_value - min_value)
        #if x != 0 else 0
    )
    
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df10[new_col_name] = normalized_values_rounded

x = ['Count of Fillings ', 'Count of Grants','Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR','R&D as a % of Sales',\
'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity','Volume of CVC deals done ','Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',\
'Number of Companies citing your patents ','Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',\
'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes']

z = list()
for i in x:
    nn = 'Normalized '+ i
    z.append(nn)
print(z)

nn

In [10]:
COI_4 = ['Volume of CVC deals done ','Share of Deals done in Disruptive Themes']
for col in COI_4:
    # Calculate min-max normalized values for selected columns
    min_value = df10[col].min()
    max_value = df10[col].max()

    # Normalized values calculation adjusted with condition
    normalized_values_rounded = df10[col].apply(lambda x: 0.01 if x < 0 else 0.01 + (x - min_value) * (1 - 0.01) / (max_value - min_value))
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df10[new_col_name] = normalized_values_rounded

# Working sheet
df10_working = df10[['CDMS ID','Count of Fillings ', 'Count of Grants','Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR',\
                    'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity','Volume of CVC deals done ','Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',\
                    'Number of Companies citing your patents ','Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',\
                    'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes','Normalized Count of Fillings ', 'Normalized Count of Grants', 'Normalized Patent Application Growth 3-year CAGR', \
                     'Normalized Patent Grants Growth 3-year CAGR', 'Normalized Share of Self-Cited Patents', \
                     'Normalized Innovation Sentiment', 'Normalized Patents Portfolio Validity', 'Normalized Volume of CVC deals done ', \
                     'Normalized Average Forward Citations ', 'Normalized Generality Index', 'Normalized Tail Innovations', \
                     'Normalized Global Technological Collaboration', 'Normalized Number of Companies citing your patents ', \
                     'Normalized Originality Index', 'Normalized Technology Cycle Time', \
                     'Normalized Share of Hiring Activity in Disruptive Themes', 'Normalized Share of Patents Granted in Disruptive Themes', \
                     'Normalized Share of Deals done in Disruptive Themes']].copy()

df10 = df10[['CDMS ID','Normalized Count of Fillings ', 'Normalized Count of Grants', 'Normalized Patent Application Growth 3-year CAGR', \
                     'Normalized Patent Grants Growth 3-year CAGR', 'Normalized Share of Self-Cited Patents', \
                     'Normalized Innovation Sentiment', 'Normalized Patents Portfolio Validity', 'Normalized Volume of CVC deals done ', \
                     'Normalized Average Forward Citations ', 'Normalized Generality Index', 'Normalized Tail Innovations', \
                     'Normalized Global Technological Collaboration', 'Normalized Number of Companies citing your patents ', \
                     'Normalized Originality Index', 'Normalized Technology Cycle Time', \
                     'Normalized Share of Hiring Activity in Disruptive Themes', 'Normalized Share of Patents Granted in Disruptive Themes', \
                     'Normalized Share of Deals done in Disruptive Themes']]
# Removing Normalized from column names

df10.columns = df10.columns.str.replace('Normalized ', '')

In [11]:
# logarithmic transformation
def log_exp(value):
    try:
        return np.log(value)
    except (TypeError, ValueError, ZeroDivisionError, OverflowError):
        return ""
    
## check all columns
Log_columns = df10.columns[1:]

for col in Log_columns:
    normalized_values_rounded = df10[col].apply(log_exp)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'log ' + col
    df10[new_col_name] = normalized_values_rounded

In [12]:
df10 = df10[['CDMS ID','log Count of Fillings ', 'log Count of Grants', 'log Patent Application Growth 3-year CAGR', \
             'log Patent Grants Growth 3-year CAGR', 'log Share of Self-Cited Patents', \
             'log Innovation Sentiment', 'log Patents Portfolio Validity', 'log Volume of CVC deals done ', \
             'log Average Forward Citations ', 'log Generality Index', 'log Tail Innovations', \
             'log Global Technological Collaboration', 'log Number of Companies citing your patents ', \
             'log Originality Index', 'log Technology Cycle Time', 'log Share of Hiring Activity in Disruptive Themes', \
             'log Share of Patents Granted in Disruptive Themes', 'log Share of Deals done in Disruptive Themes']]

# copying to working sheet
df10_working = df10_working.merge(df10,on = 'CDMS ID',how= 'left')

# removing log from names
df10.columns = df10.columns.str.replace('log ', '')

x = ['Count of Fillings ', 'Count of Grants','Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR','R&D as a % of Sales',\
'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity','Volume of CVC deals done ','Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',\
'Number of Companies citing your patents ','Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',\
'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes']


z = list()
for i in x:
    nn = 'Zscore '+ i
    z.append(nn)
print(z)

In [13]:
# Z-score computation
Zscore_columns = df10.columns[1:]
for col in Zscore_columns:
    # Calculate the mean and standard deviation of the column
    mean = df10[col].mean()
    std_dev = df10[col].std()

    # Calculate the Z-score for each value in the column
    normalized_values_rounded = (df10[col] - mean) / std_dev
    #normalized_values_rounded = normalized_values.round(2)
    

    # Add the calculated values to the original DataFrame
    new_col_name = 'Zscore ' + col
    df10[new_col_name] = normalized_values_rounded
    


df10 = df10[['CDMS ID','Zscore Count of Fillings ', 'Zscore Count of Grants', 'Zscore Patent Application Growth 3-year CAGR',\
             'Zscore Patent Grants Growth 3-year CAGR', 'Zscore Share of Self-Cited Patents', \
             'Zscore Innovation Sentiment', 'Zscore Patents Portfolio Validity', 'Zscore Volume of CVC deals done ', \
             'Zscore Average Forward Citations ', 'Zscore Generality Index', 'Zscore Tail Innovations', \
             'Zscore Global Technological Collaboration', 'Zscore Number of Companies citing your patents ', \
             'Zscore Originality Index', 'Zscore Technology Cycle Time', 'Zscore Share of Hiring Activity in Disruptive Themes', \
             'Zscore Share of Patents Granted in Disruptive Themes', 'Zscore Share of Deals done in Disruptive Themes']]

# copying to working sheet
df10_working = df10_working.merge(df10,on = 'CDMS ID',how= 'left')

# removing z-score from column names
df10.columns = df10.columns.str.replace('Zscore ', '')

# Handle Outliers
Zscore_out = df10.columns[1:]

In [14]:
Zscore_out

Index(['Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ', 'Average Forward Citations ',
       'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes',
       'Share of Deals done in Disruptive Themes'],
      dtype='object')

In [15]:


# Removing values greater than 3.5
for col in Zscore_out:
    
    # Identify outliers with Z-scores > 3.5
    outliers = df10[col] > 3.5

    # Replace outlier values with the next value just greater than 3.5
    #next_greater_value = df10.loc[df10[col] > 3.5, col].min()
    next_greater_value = 3.5
    df10.loc[outliers, col] = next_greater_value

# Removing values less than -3.5
for col in Zscore_out:
    
    # Identify outliers with Z-scores < 3.5
    outliers1 = df10[col] < -3.5

    # Replace outlier values with the next value just greater than 3.5
    #next_greater_value = df10.loc[df10[col] < -3.5, col].max()
    next_greater_value = -3.5
    df10.loc[outliers1, col] = next_greater_value

# copying to working sheet
df10_working = df10_working.merge(df10,on = 'CDMS ID',how= 'left')

In [16]:
## Min-Max
Col_interest = df10.columns[1:]

for col in Col_interest:
    # Calculate min-max normalized values for selected columns
    min_value = df10[col].min()
    max_value = df10[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = (df10[col] - min_value) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Min-max ' + col
    df10[new_col_name] = normalized_values_rounded
    


df10 = df10[["CDMS ID",'Min-max Count of Fillings ', 'Min-max Count of Grants', 'Min-max Patent Application Growth 3-year CAGR',\
             'Min-max Patent Grants Growth 3-year CAGR', 'Min-max Share of Self-Cited Patents',\
             'Min-max Innovation Sentiment', 'Min-max Patents Portfolio Validity', 'Min-max Volume of CVC deals done ',\
             'Min-max Average Forward Citations ', 'Min-max Generality Index', 'Min-max Tail Innovations',\
             'Min-max Global Technological Collaboration', 'Min-max Number of Companies citing your patents ',\
             'Min-max Originality Index', 'Min-max Technology Cycle Time', 'Min-max Share of Hiring Activity in Disruptive Themes',\
             'Min-max Share of Patents Granted in Disruptive Themes', 'Min-max Share of Deals done in Disruptive Themes']]

# copying to working sheet
df10_working = df10_working.merge(df10,on = 'CDMS ID',how= 'left')

# Removing min-max from column names
df10.columns = df10.columns.str.replace("Min-max ","")


except_column = 'CDMS ID'

# Multiply all columns by 1000 except the specified column
df10.loc[:, df10.columns != except_column] *= 1000

# Excluding CDMS in ranking
columns_to_rank = df10.columns.drop('CDMS ID')

# Calculating percent rank
pct_10 = df10[columns_to_rank].rank(pct=True)

# Modifying column names
#pct_10.columns = ['Pct_' + col for col in form.columns]

# Adding column 'A' back to the DataFrame
pct_10.insert(0, 'CDMS ID', df10['CDMS ID'])

# copying to working sheet
df10_working = df10_working.merge(df10,on = 'CDMS ID',how= 'left')

In [17]:
# preparing Innovation intensity overall score KPI
# preparing KPI for 9 columns in Innv. Intensity
selected_columns = ['Count of Fillings ', 'Count of Grants',
                    'Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR',
                    'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity',
                    'Volume of CVC deals done ']

# Define weights for each column
weights = [0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

# Create the new column 
df10['Innovation Intensity (Overall Pillar Score)'] = df10[selected_columns].mul(weights).sum(axis=1)
#df10.info();display(df10)


# preparing Innovation impact overall score KPI
# preparing KPI for 5 columns in Innv. Impact
selected_columns1 = ['Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',
                     'Number of Companies citing your patents ']

# Defined weights for each column
weights1 = [0.3, 0.3, 0.05, 0.1, 0.25]

# Create the new column 
df10['Innovation Impact (Overall Pillar Score)'] = df10[selected_columns1].mul(weights1).sum(axis=1)
#df10.info();display(df10)


# preparing Innovation Ingenuity overall score KPI
# preparing KPI for 5 columns in Innv. Ingenuity
selected_columns2 = ['Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',
                     'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes']

# Define weights for each column
weights2 = [0.25, 0.25, 0.05, 0.4, 0.05]

# Create the new column 
df10['Innovation Ingenuity (Overall Pillar Score)'] = df10[selected_columns2].mul(weights2).sum(axis=1)
#df10.info();display(df10)



## Preparing overall score
# preparing KPI for Consolidated Score by using Pillar scores
selected_columns3 = ['Innovation Intensity (Overall Pillar Score)','Innovation Impact (Overall Pillar Score)',
                    'Innovation Ingenuity (Overall Pillar Score)']

# Define weights for each column
weights3 = [0.5, 0.3, 0.2]

# Create the new column 
df10['Consolidated Score'] = df10[selected_columns3].mul(weights3).sum(axis=1)
#df10.info();display(df10)

In [18]:
df10

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Average Forward Citations,...,Number of Companies citing your patents,Originality Index,Technology Cycle Time,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score
0,1000749,634.020536,589.848337,216.300470,243.151672,486.777343,955.880629,691.365633,234.379017,371.646120,...,675.158839,830.821616,642.685469,133.966424,648.254174,0.0,527.559251,538.357633,634.376762,552.162268
1,1001749,34.766041,19.936934,77.849885,109.231942,758.309113,0.000000,602.389987,0.000000,351.586401,...,106.896143,592.018261,747.598750,NaN,NaN,0.0,165.718688,332.858224,334.904253,249.697662
2,1002130,47.466604,40.023064,29.946453,119.453322,681.634924,938.229686,448.652943,71.008156,472.187442,...,258.037715,893.215234,720.523425,NaN,509.845400,0.0,246.390482,467.508564,607.372825,384.922375
3,1002605,8.651214,8.407051,168.309790,341.560569,345.162359,972.164210,513.058486,277.857041,223.458992,...,10.781741,635.196290,784.618453,NaN,687.805302,0.0,265.222899,246.769636,630.075807,332.657501
4,1002842,271.884266,403.926479,84.398248,213.075530,653.720557,0.000000,354.038050,132.307592,441.154592,...,453.563811,731.596095,282.651404,NaN,509.742518,0.0,278.916147,484.620369,457.458882,376.335961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6988,5196234,31.353021,38.772233,166.434868,286.954123,177.084819,0.000000,605.682803,0.000000,402.281984,...,91.850487,558.811504,263.180416,NaN,574.424431,0.0,137.640712,383.097226,435.267752,270.803074
6989,5199220,49.480159,94.324719,252.558124,320.127245,537.553487,938.253252,433.257683,0.000000,958.900407,...,534.580299,736.853405,558.409283,252.744239,997.185671,0.0,276.935955,676.215635,735.327152,488.398098
6990,5221636,60.269686,73.795357,504.107445,582.101510,565.882850,0.000000,670.177961,0.000000,739.680984,...,424.908078,898.384072,458.271522,NaN,661.450124,0.0,259.039985,615.730558,603.743948,434.987950
6991,5240689,44.720703,68.229516,373.165876,344.394208,468.065832,0.000000,610.040948,0.000000,893.501495,...,455.495198,880.046832,506.773176,NaN,770.008658,0.0,202.156730,647.967119,654.708465,426.410194
6992,5255562,233.096813,167.748749,888.957969,806.857934,577.931976,0.000000,787.286696,0.000000,354.695546,...,218.273693,907.608412,532.936481,NaN,555.751988,0.0,386.272570,399.996643,582.437018,429.622681

In [19]:
# Previous rank
df10 = df10.sort_values(by='Consolidated Score', ascending=False)
df10["Rank"] = df10['Consolidated Score'].rank(ascending=False, method='first').astype(int)

# creating activity sheet
df10_activity = df10.copy()

# New rank
#df10["Rank_pct"] = df10['Consolidated Score'].rank(pct=True)

# display df
df10.info();display(df10)

# check rank
#df10.sort_values("Rank",ascending=True)

<class 'pandas.core.frame.DataFrame'>
Index: 6993 entries, 1636 to 77
Data columns (total 24 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CDMS ID                                        6993 non-null   int64
 1   Count of Fillings                              6993 non-null   float64
 2   Count of Grants                                6981 non-null   float64
 3   Patent Application Growth 3-year CAGR          6993 non-null   float64
 4   Patent Grants Growth 3-year CAGR               6984 non-null   float64
 5   Share of Self-Cited Patents                    6926 non-null   float64
 6   Innovation Sentiment                           6993 non-null   float64
 7   Patents Portfolio Validity                     6993 non-null   float64
 8   Volume of CVC deals done                       6993 non-null   float64
 9   Average Forward Citations                      6991 non-null   float64
 10  Generality Index                               6973 non-null   float64
 11  Tail Innovations                               2613 non-null   float64
 12  Global Technological Collaboration             5403 non-null   float64
 13  Number of Companies citing your patents        6965 non-null   float64
 14  Originality Index                              6980 non-null   float64
 15  Technology Cycle Time                          6988 non-null   float64
 16  Share of Hiring Activity in Disruptive Themes  2696 non-null   float64
 17  Share of Patents Granted in Disruptive Themes  6490 non-null   float64
 18  Share of Deals done in Disruptive Themes       6993 non-null   float64
 19  Innovation Intensity (Overall Pillar Score)    6993 non-null   float64
 20  Innovation Impact (Overall Pillar Score)       6993 non-null   float64
 21  Innovation Ingenuity (Overall Pillar Score)    6993 non-null   float64
 22  Consolidated Score                             6993 non-null   float64
 23  Rank                                           6993 non-null   int32
dtypes: float64(22), int32(1), int64(1)
memory usage: 1.3 MB

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Average Forward Citations,...,Originality Index,Technology Cycle Time,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score,Rank
1636,1408443,1000.000000,1000.000000,340.410507,400.609254,557.410578,936.623244,609.463755,1000.000000,623.521228,...,813.134325,495.008991,245.025100,844.381604,781.977732,784.451734,777.190619,716.138612,768.610775,1
3810,1684916,1000.000000,1000.000000,517.899311,611.193711,576.240995,961.871301,753.907365,1000.000000,654.239393,...,608.956646,251.756783,318.604454,824.763204,763.621558,842.111268,758.879289,599.194939,768.558409,2
3909,1696652,1000.000000,1000.000000,330.752396,418.458057,504.003298,909.422358,512.630971,1000.000000,788.810259,...,782.397093,500.404748,172.439219,896.247706,819.593780,767.526708,778.921442,728.801193,763.200025,3
1869,1439305,1000.000000,1000.000000,384.134777,397.811592,585.201897,946.688653,656.505614,1000.000000,652.912179,...,787.747643,482.724577,264.797891,749.591975,907.622796,797.034253,755.227215,676.075879,760.300467,4
1440,1386813,1000.000000,1000.000000,458.633883,695.456601,524.790698,952.299841,733.566659,1000.000000,685.391480,...,685.522292,196.454443,210.929667,859.111611,879.569408,836.474768,722.579247,618.663782,758.743915,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5370,2548010,15.772005,32.786248,181.140608,247.608245,NaN,0.000000,550.918464,0.000000,51.899215,...,NaN,NaN,NaN,NaN,0.000000,107.678382,179.157213,0.000000,107.586355,6989
179,1034997,2.058573,0.000000,73.562926,54.590106,NaN,996.342302,609.463755,277.857041,69.136885,...,NaN,NaN,NaN,NaN,0.000000,201.593328,20.855065,0.000000,107.053183,6990
2303,1494612,0.475819,1.354977,344.912098,390.702462,NaN,0.000000,298.422841,234.379017,269.673199,...,NaN,NaN,NaN,NaN,705.388617,127.207801,80.901960,35.269431,94.928375,6991
1563,1400722,1.426081,3.043383,0.000000,0.000000,NaN,0.000000,597.712292,0.000000,254.113006,...,NaN,643.264339,NaN,NaN,0.000000,60.665122,76.233902,160.816085,85.365949,6992
77,1014911,0.000000,0.000000,12.775899,24.452824,NaN,0.000000,984.215994,0.000000,NaN,...,NaN,NaN,NaN,NaN,0.000000,102.144472,0.000000,0.000000,51.072236,6993

df_10_working = df_qual.merge(df10_working, on='CDMS ID')
df_10_activity = df_qual.merge(df10_activity, on='CDMS ID')

In [20]:
df10

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Average Forward Citations,...,Originality Index,Technology Cycle Time,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score,Rank
1636,1408443,1000.000000,1000.000000,340.410507,400.609254,557.410578,936.623244,609.463755,1000.000000,623.521228,...,813.134325,495.008991,245.025100,844.381604,781.977732,784.451734,777.190619,716.138612,768.610775,1
3810,1684916,1000.000000,1000.000000,517.899311,611.193711,576.240995,961.871301,753.907365,1000.000000,654.239393,...,608.956646,251.756783,318.604454,824.763204,763.621558,842.111268,758.879289,599.194939,768.558409,2
3909,1696652,1000.000000,1000.000000,330.752396,418.458057,504.003298,909.422358,512.630971,1000.000000,788.810259,...,782.397093,500.404748,172.439219,896.247706,819.593780,767.526708,778.921442,728.801193,763.200025,3
1869,1439305,1000.000000,1000.000000,384.134777,397.811592,585.201897,946.688653,656.505614,1000.000000,652.912179,...,787.747643,482.724577,264.797891,749.591975,907.622796,797.034253,755.227215,676.075879,760.300467,4
1440,1386813,1000.000000,1000.000000,458.633883,695.456601,524.790698,952.299841,733.566659,1000.000000,685.391480,...,685.522292,196.454443,210.929667,859.111611,879.569408,836.474768,722.579247,618.663782,758.743915,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5370,2548010,15.772005,32.786248,181.140608,247.608245,NaN,0.000000,550.918464,0.000000,51.899215,...,NaN,NaN,NaN,NaN,0.000000,107.678382,179.157213,0.000000,107.586355,6989
179,1034997,2.058573,0.000000,73.562926,54.590106,NaN,996.342302,609.463755,277.857041,69.136885,...,NaN,NaN,NaN,NaN,0.000000,201.593328,20.855065,0.000000,107.053183,6990
2303,1494612,0.475819,1.354977,344.912098,390.702462,NaN,0.000000,298.422841,234.379017,269.673199,...,NaN,NaN,NaN,NaN,705.388617,127.207801,80.901960,35.269431,94.928375,6991
1563,1400722,1.426081,3.043383,0.000000,0.000000,NaN,0.000000,597.712292,0.000000,254.113006,...,NaN,643.264339,NaN,NaN,0.000000,60.665122,76.233902,160.816085,85.365949,6992
77,1014911,0.000000,0.000000,12.775899,24.452824,NaN,0.000000,984.215994,0.000000,NaN,...,NaN,NaN,NaN,NaN,0.000000,102.144472,0.000000,0.000000,51.072236,6993

# Loop through each column
for col in df10.columns:
    try:
        # Check if the column contains float values
        if df10[col].dtype == 'float64':
            # Round float values to integers
            df10[col] = df10[col].round().astype(int)
    except:
        print('failed', col)

print(df10)

writer = pd.ExcelWriter('IS_10 years_out_Scores_02042024.xlsx')
df_10_working.to_excel(writer, '10_years_working', index = False)
df_10_activity.to_excel(writer, '10_years_activity', index = False)
writer.close()

In [20]:
## 5 years

In [22]:
df5 = data['5_years'].copy()
df5.info(); display(df5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6996 entries, 0 to 6995
Data columns (total 25 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CDMS ID                                        6996 non-null   int64
 1   Company Name                                   6996 non-null   object
 2   Stock Ticker                                   3957 non-null   object
 3   Stock Exchange                                 3957 non-null   object
 4   Country (HQ)                                   6951 non-null   object
 5   Sector                                         6846 non-null   object
 6   Theme                                          1805 non-null   object
 7   Count of Fillings                              6996 non-null   int64
 8   Count of Grants                                6842 non-null   float64
 9   Patent Application Growth 3-year CAGR          6996 non-null   float64
 10  Patent Grants Growth 3-year CAGR               6987 non-null   float64
 11  Share of Self-Cited Patents                    6768 non-null   float64
 12  Patents Portfolio Validity                     6996 non-null   float64
 13  Average Forward Citations                      6861 non-null   float64
 14  Generality Index                               6743 non-null   float64
 15  Tail Innovations                               321 non-null    float64
 16  Global Technological Collaboration             4142 non-null   float64
 17  Number of Companies citing your patents        6364 non-null   float64
 18  Originality Index                              6949 non-null   float64
 19  Technology Cycle Time                          6974 non-null   float64
 20  Share of Patents Granted in Disruptive Themes  5494 non-null   float64
 21  Volume of CVC deals done                       6996 non-null   int64
 22  Share of Deals done in Disruptive Themes       6996 non-null   float64
 23  Innovation Sentiment                           3501 non-null   float64
 24  Share of Hiring Activity in Disruptive Themes  1930 non-null   float64
dtypes: float64(16), int64(3), object(6)
memory usage: 1.3+ MB

,CDMS ID,Company Name,Stock Ticker,Stock Exchange,Country (HQ),Sector,Theme,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,...,Tail Innovations,Global Technological Collaboration,Number of Companies citing your patents,Originality Index,Technology Cycle Time,Share of Patents Granted in Disruptive Themes,Volume of CVC deals done,Share of Deals done in Disruptive Themes,Innovation Sentiment,Share of Hiring Activity in Disruptive Themes
0,1000749,AB Volvo,VOLV B,Stockholm Stock Exchange,Sweden,Automotive,Theme - Industry - Automotive - Autonomous Veh...,3995,1000.0,4.79486,...,NaN,11.0,102.0,0.88918,9.17710,0.19200,3,0.0,0.520997,NaN
1,1001749,Aichi Corp,6345,Tokyo Stock Exchange,Japan,Automotive,NaN,96,20.0,1.51889,...,NaN,4.0,4.0,0.72780,14.87975,NaN,0,0.0,NaN,NaN
2,1002130,Aida Engineering Ltd,6118,Tokyo Stock Exchange,Japan,Industrial Goods and Machinery,NaN,81,31.0,0.55967,...,NaN,NaN,5.0,0.92522,12.10427,0.03226,0,0.0,0.882775,NaN
3,1002605,PORR AG,POS,Vienna Stock Exchange - Cash Market,Austria,Construction,NaN,14,4.0,3.56749,...,NaN,NaN,NaN,0.76640,20.68378,0.25000,2,0.0,0.730159,NaN
4,1002842,Anhui Ankai Automobile Co Ltd,000868,Shenzhen Stock Exchange,China,Automotive,NaN,386,245.0,1.65644,...,NaN,2.0,9.0,0.87869,4.39203,0.13469,1,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,5196234,Liu Ting Ting,NaN,NaN,Hong Kong (China SAR),General Business,NaN,95,76.0,3.52162,...,NaN,NaN,2.0,0.83300,2.05810,0.14474,0,0.0,NaN,NaN
6992,5199220,Trellix,NaN,NaN,United States,Technology and Communications,Theme - Technology - Cybersecurity; Theme - Te...,79,61.0,5.79372,...,NaN,NaN,14.0,0.81123,7.81148,0.98361,0,0.0,0.500000,NaN
6993,5221636,"BFLY Operations, Inc.",NaN,NaN,United States,NaN,NaN,206,76.0,14.80348,...,NaN,4.0,28.0,0.92996,6.49560,0.23684,0,0.0,NaN,NaN
6994,5240689,"i-PRO Co., Ltd",NaN,NaN,Japan,Technology and Communications,NaN,145,74.0,9.61710,...,NaN,NaN,22.0,0.92043,6.57998,0.43243,0,0.0,NaN,NaN
6995,5255562,AutoStore Technology AS,NaN,NaN,Norway,Technology and Communications,NaN,1195,214.0,39.26381,...,NaN,NaN,13.0,0.93421,6.80427,0.07944,0,0.0,NaN,NaN

In [24]:
df5 = df5[['CDMS ID'] + df5.columns[7:].to_list()]
COI5 = ['Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 
       'Share of Self-Cited Patents', 
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes']

COI5 = df5.columns[1:]

for col in COI5:
    # Calculate min-max normalized values for selected columns
    min_value = df5[col].min()
    max_value = df5[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = 0.01 + (df5[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df5[new_col_name] = normalized_values_rounded

In [25]:
COI5_2 = ['Innovation Sentiment']


for col in COI5_2:
    # Calculate min-max normalized values for selected columns
    min_value = df5[col].min()
    max_value = df5[col].max()

    # Adjusted normalized values calculation with condition
    normalized_values_rounded = np.where(
        df5[col].isna(),  # Condition to check if the value is NaN (blank)
        0.01,  # Value if condition is true
        0.01 + (df5[col] - min_value) * (1 - 0.01) / (max_value - min_value)  # Value if condition is false
    )
    
    #normalized_values_rounded = np.round(normalized_values, 2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df5[new_col_name] = normalized_values_rounded

In [26]:
COI5_3 = ['Patents Portfolio Validity']
for col in COI5_3:
    # Calculate min-max normalized values for selected columns
    min_value = df5[col].min()
    max_value = df5[col].max()

    # Step 1: Set to 0 if df5[col] < 0
    intermediate_values = df5[col].apply(lambda x: 0 if x < 0 else x)

    # Step 2: Calculate using the formula on intermediate values
    #normalized_values = 0.01 + (df5[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    normalized_values_rounded = intermediate_values.apply(
        lambda x: 0.01 + ((x - min_value) * (1 - 0.01)) / (max_value - min_value)
        #if x != 0 else 0
    )
    
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df5[new_col_name] = normalized_values_rounded
    
# for 2 more columns
COI5_4 = ['Volume of CVC deals done ','Share of Deals done in Disruptive Themes']
for col in COI5_4:
    # Calculate min-max normalized values for selected columns
    min_value = df5[col].min()
    max_value = df5[col].max()

    # Normalized values calculation adjusted with condition
    normalized_values_rounded = df5[col].apply(lambda x: 0.01 if x < 0 else 0.01 + (x - min_value) * (1 - 0.01) / (max_value - min_value))
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df5[new_col_name] = normalized_values_rounded
    

df5 = df5[['CDMS ID','Normalized Count of Fillings ', 'Normalized Count of Grants',
       'Normalized Patent Application Growth 3-year CAGR',
       'Normalized Patent Grants Growth 3-year CAGR',
       'Normalized Share of Self-Cited Patents',
       'Normalized Average Forward Citations ', 'Normalized Generality Index',
       'Normalized Tail Innovations',
       'Normalized Global Technological Collaboration',
       'Normalized Number of Companies citing your patents ',
       'Normalized Originality Index', 'Normalized Technology Cycle Time',
       'Normalized Share of Hiring Activity in Disruptive Themes',
       'Normalized Share of Patents Granted in Disruptive Themes',
        'Normalized Innovation Sentiment',
       'Normalized Patents Portfolio Validity',
       'Normalized Volume of CVC deals done ',
       'Normalized Share of Deals done in Disruptive Themes']]

### Removing Normalized from column names
df5.columns = df5.columns.str.replace('Normalized ', '')

In [27]:
## Logarithmic
def log_exp(value):
    try:
        return np.log(value)
    except (TypeError, ValueError, ZeroDivisionError, OverflowError):
        return ""

Log_columns5 = df5.columns[1:]
for col in Log_columns5:
    normalized_values_rounded = df5[col].apply(log_exp)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'log ' + col
    df5[new_col_name] = normalized_values_rounded

df5 = df5[['CDMS ID','log Count of Fillings ','log Count of Grants', 'log Patent Application Growth 3-year CAGR',
       'log Patent Grants Growth 3-year CAGR',
       'log Share of Self-Cited Patents', 'log Average Forward Citations ',
       'log Generality Index', 'log Tail Innovations',
       'log Global Technological Collaboration',
       'log Number of Companies citing your patents ', 'log Originality Index',
       'log Technology Cycle Time',
       'log Share of Hiring Activity in Disruptive Themes',
       'log Share of Patents Granted in Disruptive Themes',
       'log Innovation Sentiment',
       'log Patents Portfolio Validity', 'log Volume of CVC deals done ',
       'log Share of Deals done in Disruptive Themes']]

# Remove log from names
df5.columns = df5.columns.str.replace('log ', '')

# Z- score
Zscore_columns5 = df5.columns[1:]
for col in Zscore_columns5:
    # Calculate the mean and standard deviation of the column
    mean = df5[col].mean()
    std_dev = df5[col].std()

    # Calculate the Z-score for each value in the column
    normalized_values_rounded = (df5[col] - mean) / std_dev
    #normalized_values_rounded = normalized_values.round(2)
    

    # Add the calculated values to the original DataFrame
    new_col_name = 'Zscore ' + col
    df5[new_col_name] = normalized_values_rounded
    
df5 = df5[['CDMS ID','Zscore Count of Fillings ','Zscore Count of Grants',
       'Zscore Patent Application Growth 3-year CAGR',
       'Zscore Patent Grants Growth 3-year CAGR',
       'Zscore Share of Self-Cited Patents',
       'Zscore Average Forward Citations ', 'Zscore Generality Index',
       'Zscore Tail Innovations', 'Zscore Global Technological Collaboration',
       'Zscore Number of Companies citing your patents ',
       'Zscore Originality Index', 'Zscore Technology Cycle Time',
       'Zscore Share of Hiring Activity in Disruptive Themes',
       'Zscore Share of Patents Granted in Disruptive Themes',
       'Zscore Innovation Sentiment',
       'Zscore Patents Portfolio Validity', 'Zscore Volume of CVC deals done ',
       'Zscore Share of Deals done in Disruptive Themes']]

df5.columns = df5.columns.str.replace('Zscore ', '')

In [28]:
# Handle Outliers
Zscore_out5 = df5.columns[1:]

for col in Zscore_out5:
    
    # Identify outliers with Z-scores > 3.5
    outliers = df5[col] > 3.5

    # Replace outlier values with the next value just greater than 3.5
    next_greater_value = df5.loc[df5[col] > 3.5, col].min()
    df5.loc[outliers, col] = next_greater_value

for col in Zscore_out5:
    
    # Identify outliers with Z-scores < -3.5
    outliers1 = df5[col] < -3.5

    # Replace outlier values with the next value just greater than -3.5
    next_greater_value = df5.loc[df5[col] < -3.5, col].max()
    df5.loc[outliers1, col] = next_greater_value

In [29]:
## Min-max
Col_interest5 = df5.columns[1:]
for col in Col_interest5:
    # Calculate min-max normalized values for selected columns
    min_value = df5[col].min()
    max_value = df5[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = (df5[col] - min_value) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Min-max ' + col
    df5[new_col_name] = normalized_values_rounded

df5 = df5[["CDMS ID",'Min-max Count of Fillings ', 'Min-max Count of Grants',
       'Min-max Patent Application Growth 3-year CAGR',
       'Min-max Patent Grants Growth 3-year CAGR',
       'Min-max Share of Self-Cited Patents',
       'Min-max Average Forward Citations ', 'Min-max Generality Index',
       'Min-max Tail Innovations',
       'Min-max Global Technological Collaboration',
       'Min-max Number of Companies citing your patents ',
       'Min-max Originality Index', 'Min-max Technology Cycle Time',
       'Min-max Share of Hiring Activity in Disruptive Themes',
       'Min-max Share of Patents Granted in Disruptive Themes',
       'Min-max Innovation Sentiment',
       'Min-max Patents Portfolio Validity',
       'Min-max Volume of CVC deals done ',
       'Min-max Share of Deals done in Disruptive Themes']]

df5.columns = df5.columns.str.replace("Min-max ","")

# Multiply all columns by 1000 except the specified column

except_column5 = 'CDMS ID'

df5.loc[:, df5.columns != except_column5] *= 1000

In [30]:
# preparing KPI
selected_columns5 = ['Count of Fillings ', 'Count of Grants',
                    'Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR',
                    'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity',
                    'Volume of CVC deals done ']

# Define weights for each column
weights11 = [0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

# Create the new column 
df5['Innovation Intensity (Overall Pillar Score)'] = df5[selected_columns5].mul(weights11).sum(axis=1)
#df5.info();display(df5)

# preparing KPI
selected_columns51 = ['Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',
                     'Number of Companies citing your patents ']

# Define weights for each column
weights51 = [0.3, 0.3, 0.05, 0.1, 0.25]

# Create the new column 
df5['Innovation Impact (Overall Pillar Score)'] = df5[selected_columns51].mul(weights51).sum(axis=1)
#df5.info();display(df5)

# preparing KPI
selected_columns52 = ['Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',
                     'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes']

# Define weights for each column
weights52 = [0.25, 0.25, 0.05, 0.4, 0.05]

# Create the new column 
df5['Innovation Ingenuity (Overall Pillar Score)'] = df5[selected_columns52].mul(weights52).sum(axis=1)
#df5.info();display(df5)

# preparing KPI
selected_columns53 = ['Innovation Intensity (Overall Pillar Score)','Innovation Impact (Overall Pillar Score)',
                    'Innovation Ingenuity (Overall Pillar Score)']

# Define weights for each column
weights53 = [0.5, 0.3, 0.2]

# Create the new column 
df5['Consolidated Score'] = df5[selected_columns53].mul(weights53).sum(axis=1)
#df5.info();display(df5)

In [31]:
df5

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Average Forward Citations,Generality Index,Tail Innovations,Global Technological Collaboration,...,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score
0,1000749,657.413771,566.010674,216.015722,242.878648,427.073708,307.610150,905.232459,NaN,24.857407,...,NaN,649.608746,941.231924,699.535441,291.773149,0.0,526.535748,547.172483,581.628605,543.745340
1,1001749,29.993447,21.193815,77.747400,109.109290,674.763528,337.783280,885.195356,NaN,7.556017,...,NaN,NaN,0.000000,447.816899,0.000000,0.0,141.181164,389.697169,288.755735,245.250880
2,1002130,25.320639,33.018502,29.907030,119.319193,732.061128,394.888913,935.166459,NaN,NaN,...,NaN,305.563932,987.019328,504.124448,0.000000,0.0,248.910941,427.088775,473.691420,347.320387
3,1002605,3.925692,3.414121,168.088218,341.177045,NaN,NaN,NaN,NaN,NaN,...,NaN,704.672821,968.866383,662.690713,215.390631,0.0,237.089262,0.000000,607.257778,239.996186
4,1002842,113.012088,216.505218,84.287142,212.836277,459.025715,355.978665,933.474929,NaN,2.528297,...,NaN,576.702221,0.000000,503.214477,121.588597,0.0,203.998682,435.078588,502.926552,333.108228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,5196234,29.683216,78.368695,166.215765,286.631915,NaN,497.339693,905.634737,NaN,NaN,...,NaN,591.387378,0.000000,202.701755,0.000000,0.0,87.165326,429.046975,444.576136,261.211983
6992,5199220,24.694445,63.758735,252.225645,319.767789,608.959492,678.824907,781.474238,NaN,NaN,...,NaN,996.443560,938.253252,614.254421,0.000000,0.0,291.036696,504.906611,681.488609,433.288053
6993,5221636,63.046406,78.368695,503.443813,581.447894,541.132387,626.408857,946.588261,NaN,7.556017,...,NaN,693.346945,0.000000,578.332007,0.000000,0.0,248.718630,574.838348,591.791626,415.169145
6994,5240689,44.974522,76.448149,372.674622,344.007503,460.191338,653.361968,924.722191,NaN,NaN,...,NaN,820.471363,0.000000,523.811193,0.000000,0.0,194.353000,562.589161,640.198395,393.992927
6995,5255562,292.672006,194.166522,887.787702,805.951949,551.011773,326.160632,839.184291,NaN,NaN,...,NaN,471.265613,0.000000,670.860565,0.000000,0.0,388.928904,413.042383,507.280061,419.833179

In [32]:
# # Previous rank
df5 = df5.sort_values(by='Consolidated Score', ascending=False)
df5["Rank"] = df5['Consolidated Score'].rank(ascending=False, method='first').astype(int)

# New rank
#df5["Rank_pct"] = df5['Consolidated Score'].rank(pct=True)

df5.info();display(df5)

<class 'pandas.core.frame.DataFrame'>
Index: 6996 entries, 3810 to 1563
Data columns (total 24 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CDMS ID                                        6996 non-null   int64
 1   Count of Fillings                              6996 non-null   float64
 2   Count of Grants                                6842 non-null   float64
 3   Patent Application Growth 3-year CAGR          6996 non-null   float64
 4   Patent Grants Growth 3-year CAGR               6987 non-null   float64
 5   Share of Self-Cited Patents                    6768 non-null   float64
 6   Average Forward Citations                      6861 non-null   float64
 7   Generality Index                               6743 non-null   float64
 8   Tail Innovations                               321 non-null    float64
 9   Global Technological Collaboration             4142 non-null   float64
 10  Number of Companies citing your patents        6364 non-null   float64
 11  Originality Index                              6949 non-null   float64
 12  Technology Cycle Time                          6974 non-null   float64
 13  Share of Hiring Activity in Disruptive Themes  1930 non-null   float64
 14  Share of Patents Granted in Disruptive Themes  5494 non-null   float64
 15  Innovation Sentiment                           6996 non-null   float64
 16  Patents Portfolio Validity                     6996 non-null   float64
 17  Volume of CVC deals done                       6996 non-null   float64
 18  Share of Deals done in Disruptive Themes       6996 non-null   float64
 19  Innovation Intensity (Overall Pillar Score)    6996 non-null   float64
 20  Innovation Impact (Overall Pillar Score)       6996 non-null   float64
 21  Innovation Ingenuity (Overall Pillar Score)    6996 non-null   float64
 22  Consolidated Score                             6996 non-null   float64
 23  Rank                                           6996 non-null   int32
dtypes: float64(22), int32(1), int64(1)
memory usage: 1.3 MB

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Average Forward Citations,Generality Index,Tail Innovations,Global Technological Collaboration,...,Share of Patents Granted in Disruptive Themes,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score,Rank
3810,1684916,1000.000000,1000.000000,517.217523,610.507429,539.901046,701.050202,829.056590,394.810179,696.523294,...,801.535015,974.893362,672.228345,1000.000000,757.141024,831.474771,798.424876,578.348767,770.934601,1
1869,1439305,1000.000000,1000.000000,383.629083,397.364907,540.294406,587.491394,875.748142,1000.000000,184.435113,...,778.627608,963.646422,680.041352,932.002244,941.091444,789.697841,757.415372,657.785295,753.630591,2
1440,1386813,1000.000000,1000.000000,458.030115,694.675704,495.430085,704.297281,855.924752,58.467875,46.455708,...,858.496017,937.183685,646.071960,946.527530,897.522685,817.791908,725.635574,630.257701,752.638166,3
4915,2144860,763.664944,791.545602,912.536856,738.956397,549.493159,530.495771,940.726534,728.332615,5.046945,...,924.408798,887.396021,703.835150,885.081961,809.494460,778.772064,692.686977,733.966246,743.985374,4
4656,1786069,1000.000000,1000.000000,450.311539,512.723732,420.444093,367.042257,925.792778,NaN,1000.000000,...,807.078605,989.187615,654.298598,644.706393,829.244191,767.167197,737.850510,676.906400,740.320032,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,2298531,0.000000,0.000000,0.899810,13.829071,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,734.460790,0.000000,0.000000,74.918967,0.000000,0.000000,37.459484,6992
6700,4286544,1.311827,5.675759,0.000000,0.000000,NaN,394.888913,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,0.000000,1.397517,118.466674,0.000000,36.238761,6993
2860,1564761,0.000000,NaN,6.953264,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,35.973980,215.390631,0.000000,25.831788,0.000000,82.589491,29.433792,6994
6614,4256057,0.000000,1.140949,1.555806,13.277055,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,215.390631,0.000000,23.250539,0.000000,84.146421,28.454554,6995
1563,1400722,0.656323,3.414121,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,186.458708,0.000000,0.000000,19.459960,0.000000,0.000000,9.729980,6996

In [33]:
## 3 Years

In [34]:
df3 = data['3_years'].copy()
df3.info(); display(df3)

df3 = df3[['CDMS ID'] + df3.columns[7:].to_list()]

COI3 = ['Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 
       'Share of Self-Cited Patents', 
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes']
for col in COI3:
    # Calculate min-max normalized values for selected columns
    min_value = df3[col].min()
    max_value = df3[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = 0.01 + (df3[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df3[new_col_name] = normalized_values_rounded


COI3_2 = ['Innovation Sentiment']


for col in COI3_2:
    # Calculate min-max normalized values for selected columns
    min_value = df3[col].min()
    max_value = df3[col].max()

    # Adjusted normalized values calculation with condition
    normalized_values_rounded = np.where(
        df3[col].isna(),  # Condition to check if the value is NaN (blank)
        0.01,  # Value if condition is true
        0.01 + (df3[col] - min_value) * (1 - 0.01) / (max_value - min_value)  # Value if condition is false
    )
    
    #normalized_values_rounded = np.round(normalized_values, 2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df3[new_col_name] = normalized_values_rounded
    
    
COI3_3 = ['Patents Portfolio Validity']
for col in COI3_3:
    # Calculate min-max normalized values for selected columns
    min_value = df3[col].min()
    max_value = df3[col].max()

    # Step 1: Set to 0 if df3[col] < 0
    intermediate_values = df3[col].apply(lambda x: 0 if x < 0 else x)

    # Step 2: Calculate using the formula on intermediate values
    #normalized_values = 0.01 + (df3[col] - min_value) * (1 - 0.01) / (max_value - min_value)
    normalized_values_rounded = intermediate_values.apply(
        lambda x: 0.01 + ((x - min_value) * (1 - 0.01)) / (max_value - min_value)
        #if x != 0 else 0
    )
    
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df3[new_col_name] = normalized_values_rounded

COI3_4 = ['Volume of CVC deals done ','Share of Deals done in Disruptive Themes']
for col in COI3_4:
    # Calculate min-max normalized values for selected columns
    min_value = df3[col].min()
    max_value = df3[col].max()

    # Normalized values calculation adjusted with condition
    normalized_values_rounded = df3[col].apply(lambda x: 0.01 if x < 0 else 0.01 + (x - min_value) * (1 - 0.01) / (max_value - min_value))
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Normalized ' + col
    df3[new_col_name] = normalized_values_rounded

df3 = df3[['CDMS ID','Normalized Count of Fillings ', 'Normalized Count of Grants',
       'Normalized Patent Application Growth 3-year CAGR',
       'Normalized Patent Grants Growth 3-year CAGR',
       'Normalized Share of Self-Cited Patents',
       'Normalized Average Forward Citations ', 'Normalized Generality Index',
       'Normalized Tail Innovations',
       'Normalized Global Technological Collaboration',
       'Normalized Number of Companies citing your patents ',
       'Normalized Originality Index', 'Normalized Technology Cycle Time',
       'Normalized Share of Hiring Activity in Disruptive Themes',
       'Normalized Share of Patents Granted in Disruptive Themes',
        'Normalized Innovation Sentiment',
       'Normalized Patents Portfolio Validity',
       'Normalized Volume of CVC deals done ',
       'Normalized Share of Deals done in Disruptive Themes']]

### Removing Normalized from column names
df3.columns = df3.columns.str.replace('Normalized ', '')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6996 entries, 0 to 6995
Data columns (total 25 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CDMS ID                                        6996 non-null   int64
 1   Company Name                                   6996 non-null   object
 2   Stock Ticker                                   3957 non-null   object
 3   Stock Exchange                                 3957 non-null   object
 4   Country (HQ)                                   6951 non-null   object
 5   Sector                                         6846 non-null   object
 6   Theme                                          1805 non-null   object
 7   Count of Fillings                              6831 non-null   float64
 8   Count of Grants                                6141 non-null   float64
 9   Patent Application Growth 3-year CAGR          6831 non-null   float64
 10  Patent Grants Growth 3-year CAGR               6823 non-null   float64
 11  Share of Self-Cited Patents                    6096 non-null   float64
 12  Patents Portfolio Validity                     6831 non-null   float64
 13  Average Forward Citations                      5763 non-null   float64
 14  Generality Index                               5473 non-null   float64
 15  Tail Innovations                               20 non-null     float64
 16  Global Technological Collaboration             3103 non-null   float64
 17  Number of Companies citing your patents        4123 non-null   float64
 18  Originality Index                              6603 non-null   float64
 19  Technology Cycle Time                          6679 non-null   float64
 20  Share of Patents Granted in Disruptive Themes  3912 non-null   float64
 21  Volume of CVC deals done                       6996 non-null   int64
 22  Share of Deals done in Disruptive Themes       6996 non-null   float64
 23  Innovation Sentiment                           3175 non-null   float64
 24  Share of Hiring Activity in Disruptive Themes  630 non-null    float64
dtypes: float64(17), int64(2), object(6)
memory usage: 1.3+ MB

,CDMS ID,Company Name,Stock Ticker,Stock Exchange,Country (HQ),Sector,Theme,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,...,Tail Innovations,Global Technological Collaboration,Number of Companies citing your patents,Originality Index,Technology Cycle Time,Share of Patents Granted in Disruptive Themes,Volume of CVC deals done,Share of Deals done in Disruptive Themes,Innovation Sentiment,Share of Hiring Activity in Disruptive Themes
0,1000749,AB Volvo,VOLV B,Stockholm Stock Exchange,Sweden,Automotive,Theme - Industry - Automotive - Autonomous Veh...,2244.0,325.0,4.79486,...,NaN,9.0,43.0,0.88216,9.18226,0.28000,1,0.0,0.715686,NaN
1,1001749,Aichi Corp,6345,Tokyo Stock Exchange,Japan,Automotive,NaN,14.0,4.0,1.51889,...,NaN,NaN,1.0,0.42044,15.41752,NaN,0,0.0,NaN,NaN
2,1002130,Aida Engineering Ltd,6118,Tokyo Stock Exchange,Japan,Industrial Goods and Machinery,NaN,25.0,9.0,0.55967,...,NaN,NaN,1.0,0.92698,8.70744,NaN,0,0.0,NaN,NaN
3,1002605,PORR AG,POS,Vienna Stock Exchange - Cash Market,Austria,Construction,NaN,8.0,1.0,3.56749,...,NaN,NaN,NaN,0.54082,14.86927,NaN,2,0.0,0.777778,NaN
4,1002842,Anhui Ankai Automobile Co Ltd,000868,Shenzhen Stock Exchange,China,Automotive,NaN,96.0,28.0,1.65644,...,NaN,2.0,1.0,0.84690,3.52267,0.28571,0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,5196234,Liu Ting Ting,NaN,NaN,Hong Kong (China SAR),General Business,NaN,5.0,1.0,3.52162,...,NaN,NaN,NaN,0.97222,0.76660,NaN,0,0.0,NaN,NaN
6992,5199220,Trellix,NaN,NaN,United States,Technology and Communications,Theme - Technology - Cybersecurity; Theme - Te...,36.0,25.0,5.79372,...,NaN,NaN,5.0,0.81116,7.13073,1.00000,0,0.0,0.500000,NaN
6993,5221636,"BFLY Operations, Inc.",NaN,NaN,United States,NaN,NaN,86.0,18.0,14.80348,...,NaN,4.0,2.0,0.92220,7.97719,0.22222,0,0.0,NaN,NaN
6994,5240689,"i-PRO Co., Ltd",NaN,NaN,Japan,Technology and Communications,NaN,59.0,13.0,9.61710,...,NaN,NaN,8.0,0.90895,8.01864,0.46154,0,0.0,NaN,NaN
6995,5255562,AutoStore Technology AS,NaN,NaN,Norway,Technology and Communications,NaN,596.0,66.0,39.26381,...,NaN,NaN,5.0,0.92963,6.60123,0.09091,0,0.0,NaN,NaN

In [35]:
## Logarithmic
def log_exp(value):
    try:
        return np.log(value)
    except (TypeError, ValueError, ZeroDivisionError, OverflowError):
        return ""

Log_columns = df3.columns[1:]
for col in Log_columns:
    normalized_values_rounded = df3[col].apply(log_exp)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'log ' + col
    df3[new_col_name] = normalized_values_rounded
    
df3 = df3[['CDMS ID','log Count of Fillings ','log Count of Grants', 'log Patent Application Growth 3-year CAGR',
       'log Patent Grants Growth 3-year CAGR',
       'log Share of Self-Cited Patents', 'log Average Forward Citations ',
       'log Generality Index', 'log Tail Innovations',
       'log Global Technological Collaboration',
       'log Number of Companies citing your patents ', 'log Originality Index',
       'log Technology Cycle Time',
       'log Share of Hiring Activity in Disruptive Themes',
       'log Share of Patents Granted in Disruptive Themes',
       'log Innovation Sentiment',
       'log Patents Portfolio Validity', 'log Volume of CVC deals done ',
       'log Share of Deals done in Disruptive Themes']]

# Remove log from names
df3.columns = df3.columns.str.replace('log ', '')

# Z- score
Zscore_columns3 = df3.columns[1:]
for col in Zscore_columns3:
    # Calculate the mean and standard deviation of the column
    mean = df3[col].mean()
    std_dev = df3[col].std()

    # Calculate the Z-score for each value in the column
    normalized_values_rounded = (df3[col] - mean) / std_dev
    #normalized_values_rounded = normalized_values.round(2)
    

    # Add the calculated values to the original DataFrame
    new_col_name = 'Zscore ' + col
    df3[new_col_name] = normalized_values_rounded

    
df3 = df3[['CDMS ID','Zscore Count of Fillings ','Zscore Count of Grants',
       'Zscore Patent Application Growth 3-year CAGR',
       'Zscore Patent Grants Growth 3-year CAGR',
       'Zscore Share of Self-Cited Patents',
       'Zscore Average Forward Citations ', 'Zscore Generality Index',
       'Zscore Tail Innovations', 'Zscore Global Technological Collaboration',
       'Zscore Number of Companies citing your patents ',
       'Zscore Originality Index', 'Zscore Technology Cycle Time',
       'Zscore Share of Hiring Activity in Disruptive Themes',
       'Zscore Share of Patents Granted in Disruptive Themes',
       'Zscore Innovation Sentiment',
       'Zscore Patents Portfolio Validity', 'Zscore Volume of CVC deals done ',
       'Zscore Share of Deals done in Disruptive Themes']]

df3.columns = df3.columns.str.replace('Zscore ', '')

In [36]:
# Handle Outliers
Zscore_out3 = ['Count of Fillings ','Count of Grants', 'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes', 
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ',
       'Share of Deals done in Disruptive Themes']
for col in Zscore_out3:
    
    # Identify outliers with Z-scores > 3.5
    outliers = df3[col] > 3.5

    # Replace outlier values with the next value just greater than 3.5
    next_greater_value = df3.loc[df3[col] > 3.5, col].min()
    df3.loc[outliers, col] = next_greater_value


for col in Zscore_out3:
    
    # Identify outliers with Z-scores < -3.5
    outliers1 = df3[col] < -3.5

    # Replace outlier values with the next value just greater than -3.5
    next_greater_value = df3.loc[df3[col] < -3.5, col].max()
    df3.loc[outliers1, col] = next_greater_value

In [37]:
## Min-max
Col_interest3 = df3.columns[1:]
for col in Col_interest3:
    # Calculate min-max normalized values for selected columns
    min_value = df3[col].min()
    max_value = df3[col].max()

    # Normalized values calculation adjusted
    normalized_values_rounded = (df3[col] - min_value) / (max_value - min_value)
    #normalized_values_rounded = normalized_values.round(2)

    # Add the calculated values to the original DataFrame
    new_col_name = 'Min-max ' + col
    df3[new_col_name] = normalized_values_rounded

df3 = df3[["CDMS ID",'Min-max Count of Fillings ', 'Min-max Count of Grants',
       'Min-max Patent Application Growth 3-year CAGR',
       'Min-max Patent Grants Growth 3-year CAGR',
       'Min-max Share of Self-Cited Patents',
       'Min-max Average Forward Citations ', 'Min-max Generality Index',
       'Min-max Tail Innovations',
       'Min-max Global Technological Collaboration',
       'Min-max Number of Companies citing your patents ',
       'Min-max Originality Index', 'Min-max Technology Cycle Time',
       'Min-max Share of Hiring Activity in Disruptive Themes',
       'Min-max Share of Patents Granted in Disruptive Themes',
       'Min-max Innovation Sentiment',
       'Min-max Patents Portfolio Validity',
       'Min-max Volume of CVC deals done ',
       'Min-max Share of Deals done in Disruptive Themes']]

df3.columns = df3.columns.str.replace("Min-max ","")

# Multiply all columns by 1000 except the specified column

except_column3 = 'CDMS ID'

df3.loc[:, df3.columns != except_column3] *= 1000

In [38]:
# preparing KPI
selected_columns3 = ['Count of Fillings ', 'Count of Grants',
                    'Patent Application Growth 3-year CAGR','Patent Grants Growth 3-year CAGR',
                    'Share of Self-Cited Patents','Innovation Sentiment','Patents Portfolio Validity',
                    'Volume of CVC deals done ']

# Define weights for each column
weights3 = [0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

# Create the new column 
df3['Innovation Intensity (Overall Pillar Score)'] = df3[selected_columns3].mul(weights3).sum(axis=1)
#df3.info();display(df3)



# preparing KPI
selected_columns31 = ['Average Forward Citations ','Generality Index','Tail Innovations','Global Technological Collaboration',
                     'Number of Companies citing your patents ']

# Define weights for each column
weights31 = [0.3, 0.3, 0.05, 0.1, 0.25]

# Create the new column 
df3['Innovation Impact (Overall Pillar Score)'] = df3[selected_columns31].mul(weights31).sum(axis=1)
#df3.info();display(df3)



# preparing KPI
selected_columns32 = ['Originality Index','Technology Cycle Time','Share of Hiring Activity in Disruptive Themes',
                     'Share of Patents Granted in Disruptive Themes','Share of Deals done in Disruptive Themes']

# Define weights for each column
weights32 = [0.25, 0.25, 0.05, 0.4, 0.05]

# Create the new column 
df3['Innovation Ingenuity (Overall Pillar Score)'] = df3[selected_columns32].mul(weights32).sum(axis=1)
#df3.info();display(df3)



# preparing KPI
selected_columns33 = ['Innovation Intensity (Overall Pillar Score)','Innovation Impact (Overall Pillar Score)',
                    'Innovation Ingenuity (Overall Pillar Score)']

# Define weights for each column
weights33 = [0.5, 0.3, 0.2]

# Create the new column 
df3['Consolidated Score'] = df3[selected_columns33].mul(weights33).sum(axis=1)
df3.info();display(df3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6996 entries, 0 to 6995
Data columns (total 23 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   CDMS ID                                        6996 non-null   int64
 1   Count of Fillings                              6831 non-null   float64
 2   Count of Grants                                6141 non-null   float64
 3   Patent Application Growth 3-year CAGR          6831 non-null   float64
 4   Patent Grants Growth 3-year CAGR               6823 non-null   float64
 5   Share of Self-Cited Patents                    6096 non-null   float64
 6   Average Forward Citations                      5763 non-null   float64
 7   Generality Index                               5473 non-null   float64
 8   Tail Innovations                               20 non-null     float64
 9   Global Technological Collaboration             3103 non-null   float64
 10  Number of Companies citing your patents        4123 non-null   float64
 11  Originality Index                              6603 non-null   float64
 12  Technology Cycle Time                          6679 non-null   float64
 13  Share of Hiring Activity in Disruptive Themes  630 non-null    float64
 14  Share of Patents Granted in Disruptive Themes  3912 non-null   float64
 15  Innovation Sentiment                           6996 non-null   float64
 16  Patents Portfolio Validity                     6831 non-null   float64
 17  Volume of CVC deals done                       6996 non-null   float64
 18  Share of Deals done in Disruptive Themes       6996 non-null   float64
 19  Innovation Intensity (Overall Pillar Score)    6996 non-null   float64
 20  Innovation Impact (Overall Pillar Score)       6996 non-null   float64
 21  Innovation Ingenuity (Overall Pillar Score)    6996 non-null   float64
 22  Consolidated Score                             6996 non-null   float64
dtypes: float64(22), int64(1)
memory usage: 1.2 MB

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Average Forward Citations,Generality Index,Tail Innovations,Global Technological Collaboration,...,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score
0,1000749,710.286889,540.885959,213.727269,242.878648,417.602850,338.166910,952.049857,NaN,36.473724,...,NaN,727.513611,967.063487,605.079378,226.857768,0.0,517.555510,590.743237,636.516516,563.304029
1,1001749,8.233502,9.721772,76.595542,109.109290,704.817557,255.754225,811.208327,NaN,NaN,...,NaN,NaN,0.000000,580.695820,0.000000,0.0,150.712876,320.088766,243.861791,220.155426
2,1002130,15.106967,25.463632,29.142303,119.319193,752.705153,353.120395,981.582630,NaN,NaN,...,NaN,NaN,0.000000,495.172277,0.000000,0.0,147.748012,400.410908,351.154290,264.228137
3,1002605,4.448464,0.000000,166.196484,341.177045,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,974.695003,181.028829,356.992027,0.0,202.898632,0.000000,287.307732,158.910862
4,1002842,57.550566,80.633657,83.082100,212.836277,449.266444,259.298601,985.764854,NaN,4.677971,...,NaN,731.789059,0.000000,628.110873,0.000000,0.0,164.966414,373.986834,567.968682,308.272994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6991,5196234,2.546306,0.000000,164.339473,286.631915,NaN,963.439635,743.225097,NaN,NaN,...,NaN,NaN,0.000000,100.322551,0.000000,0.0,55.638655,511.999420,244.819683,230.383090
6992,5199220,21.897069,72.367992,249.635727,319.767789,682.791878,624.484224,916.554731,NaN,NaN,...,NaN,1000.000000,938.253252,541.184309,0.000000,0.0,292.016308,525.461991,713.611849,446.369121
6993,5221636,51.763768,52.457492,498.728362,581.447894,621.770936,628.642108,964.363241,NaN,13.929616,...,NaN,678.729721,0.000000,632.374567,0.000000,0.0,254.276428,500.850651,615.983318,400.590073
6994,5240689,35.833894,37.665089,369.072347,344.007503,439.652387,602.260803,961.092243,NaN,NaN,...,NaN,833.898642,0.000000,560.727591,0.000000,0.0,186.045779,558.512195,675.730070,395.722562
6995,5255562,289.809702,173.798875,879.741391,805.951949,604.244692,284.107877,878.523185,NaN,NaN,...,NaN,494.222083,0.000000,582.946056,0.000000,0.0,380.010124,411.939623,531.290389,419.845027

In [39]:
# Assigning Rankl
df3 = df3.sort_values(by='Consolidated Score', ascending=False)
df3["Rank"] = df3['Consolidated Score'].rank(ascending=False, method='first').astype(int)

# New rank
#df3["Rank_pct"] = df3['Consolidated Score'].rank(pct=True)

# check rank
df10.sort_values("Rank",ascending=True)

,CDMS ID,Count of Fillings,Count of Grants,Patent Application Growth 3-year CAGR,Patent Grants Growth 3-year CAGR,Share of Self-Cited Patents,Innovation Sentiment,Patents Portfolio Validity,Volume of CVC deals done,Average Forward Citations,...,Originality Index,Technology Cycle Time,Share of Hiring Activity in Disruptive Themes,Share of Patents Granted in Disruptive Themes,Share of Deals done in Disruptive Themes,Innovation Intensity (Overall Pillar Score),Innovation Impact (Overall Pillar Score),Innovation Ingenuity (Overall Pillar Score),Consolidated Score,Rank
1636,1408443,1000,1000.000000,340,400.609254,557.410578,937,609,1000,623.521228,...,813.134325,495.008991,245.025100,844.381604,782,784,777,716,769,1
3810,1684916,1000,1000.000000,518,611.193711,576.240995,962,754,1000,654.239393,...,608.956646,251.756783,318.604454,824.763204,764,842,759,599,769,2
3909,1696652,1000,1000.000000,331,418.458057,504.003298,909,513,1000,788.810259,...,782.397093,500.404748,172.439219,896.247706,820,768,779,729,763,3
1869,1439305,1000,1000.000000,384,397.811592,585.201897,947,657,1000,652.912179,...,787.747643,482.724577,264.797891,749.591975,908,797,755,676,760,4
1440,1386813,1000,1000.000000,459,695.456601,524.790698,952,734,1000,685.391480,...,685.522292,196.454443,210.929667,859.111611,880,836,723,619,759,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5370,2548010,16,32.786248,181,247.608245,NaN,0,551,0,51.899215,...,NaN,NaN,NaN,NaN,0,108,179,0,108,6989
179,1034997,2,0.000000,74,54.590106,NaN,996,609,278,69.136885,...,NaN,NaN,NaN,NaN,0,202,21,0,107,6990
2303,1494612,0,1.354977,345,390.702462,NaN,0,298,234,269.673199,...,NaN,NaN,NaN,NaN,705,127,81,35,95,6991
1563,1400722,1,3.043383,0,0.000000,NaN,0,598,0,254.113006,...,NaN,643.264339,NaN,NaN,0,61,76,161,85,6992
77,1014911,0,0.000000,13,24.452824,NaN,0,984,0,NaN,...,NaN,NaN,NaN,NaN,0,102,0,0,51,6993

In [40]:
df10.columns

Index(['CDMS ID', 'Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ', 'Average Forward Citations ',
       'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes',
       'Share of Deals done in Disruptive Themes',
       'Innovation Intensity (Overall Pillar Score)',
       'Innovation Impact (Overall Pillar Score)',
       'Innovation Ingenuity (Overall Pillar Score)', 'Consolidated Score',
       'Rank'],
      dtype='object')

In [41]:
# Preparing final sheets

merged_df_10 = pd.merge(df10, df_qual, on='CDMS ID')

# 
column_order = ['Rank','CDMS ID','Company Name', 'Stock Ticker ', 'Stock Exchange ',
       'Country (HQ)', 'Sector', 'Theme ', 'Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes', 
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ', 'Share of Deals done in Disruptive Themes',
       'Innovation Intensity (Overall Pillar Score)',
       'Innovation Impact (Overall Pillar Score)',
       'Innovation Ingenuity (Overall Pillar Score)', 'Consolidated Score',] 
final_df_10 = merged_df_10[column_order]



merged_df_5 = pd.merge(df5, df_qual, on='CDMS ID')

column_order = ['Rank','CDMS ID','Company Name', 'Stock Ticker ', 'Stock Exchange ',
       'Country (HQ)', 'Sector', 'Theme ', 'Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes', 
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ', 'Share of Deals done in Disruptive Themes',
       'Innovation Intensity (Overall Pillar Score)',
       'Innovation Impact (Overall Pillar Score)',
       'Innovation Ingenuity (Overall Pillar Score)', 'Consolidated Score',] 
final_df_5 = merged_df_5[column_order]



merged_df_3 = pd.merge(df3, df_qual, on='CDMS ID')

column_order = ['Rank','CDMS ID','Company Name', 'Stock Ticker ', 'Stock Exchange ',
       'Country (HQ)', 'Sector', 'Theme ', 'Count of Fillings ', 'Count of Grants',
       'Patent Application Growth 3-year CAGR',
       'Patent Grants Growth 3-year CAGR', 'Share of Self-Cited Patents',
       'Average Forward Citations ', 'Generality Index', 'Tail Innovations',
       'Global Technological Collaboration',
       'Number of Companies citing your patents ', 'Originality Index',
       'Technology Cycle Time',
       'Share of Hiring Activity in Disruptive Themes',
       'Share of Patents Granted in Disruptive Themes', 
       'Innovation Sentiment', 'Patents Portfolio Validity',
       'Volume of CVC deals done ', 'Share of Deals done in Disruptive Themes',
       'Innovation Intensity (Overall Pillar Score)',
       'Innovation Impact (Overall Pillar Score)',
       'Innovation Ingenuity (Overall Pillar Score)', 'Consolidated Score',] 
final_df_3 = merged_df_3[column_order]

In [42]:
writer = pd.ExcelWriter('IS_out_Scores_28012025.xlsx')
final_df_10.to_excel(writer, '10_years', index = False)
final_df_5.to_excel(writer, '5_years', index = False)
final_df_3.to_excel(writer, '3_years', index = False)
writer.close()